[[buildpacks]]
id = "gcr.io/paketo-buildpacks/ca-certificates"
version = "3.8.4"

[[buildpacks]]
id = "paketobuildpacks/graalvm"
version = "8.4.2"

[[buildpacks]]
id = "paketobuildpacks/native-image"
version = "5.14.2"

[stack]
id = "heroku-20"
run-image = "heroku/builder:24"
build-image = "heroku/builder:24"

[[mapping]]
id = "jdk"
version = "17.0.9"
uri = "http://10.8.0.6/Downloads/graalvm-community-jdk-17.0.9_linux-x64_bin.tar.gz"

[[mapping]]
id = "jre"
version = "17.0.7"
uri = "http://10.8.0.6/Downloads/bellsoft-jre17.0.7+7-linux-amd64.tar.gz"
