server:
  port: 8082
  ssl:
    enabled-protocols: TLSv1.2,TLSv1.3
    enabled: false
spring:
  application:
    name: Dialer
  config:
    import: "optional:configserver:"
  cloud:
    zookeeper:
      enabled: true
      connect-string: zoo2:2181
      discovery:
        enabled: true
        register: true
        root: /big-serv
      config:
        enabled: false
        root: /big-conf
        defaultContext: application
        profile-separator: ','
    config:
      server:
        native:
          search-locations: classpath:/config
#        git:
#          uri: https://github.com/spring-cloud-samples/config-repo
#      profile: dev
  h2:
    console:
      enabled: false
      settings:
        web-allow-others: false
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: 1234567
    driverClassName: org.h2.Driver
    tomcat:
      resources:
        # noinspection SpringBootApplicationYaml
        use-vfs: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        native_support: true
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: false
        format_sql: true
        use_sql_comments: true
        compile-time-hibernate-proxies: true
        bytecode:
          provider: javassist
info:
  hosts:
    - command: /usr/bin/docker exec esb expressvpn
      name: esb
      local-host: false
      proxy-host: 127.0.0.1
      proxy-port: 1087
      enabled: true
    - command: /usr/bin/ssh -i /home/lucloner/.ssh/id_ed25519 lucloner@192.168.71.207 expressvpn
      name: rpi
      local-host: false
      proxy-host: 192.168.71.207
      proxy-port: 20171
      enabled: true
    - command: /usr/bin/ssh -i /home/lucloner/.ssh/id_rsa lucloner@192.168.4.90 expressvpn
      name: air
      local-host: false
      proxy-host: 192.168.4.90
      proxy-port: 60987
      enabled: true
  urls:
    - https://youtube.com
    - https://twitter.com
    - https://google.com
    - https://bing.com
    - https://baidu.com
    - https://duckduckgo.com
  supportIPv6: false
  tolerance: 4
  interval: 10
  dns:
    - 8.8.8.8
    - 1.1.1.1
    - 208.67.222.222
    - 192.168.4.254

