server:
  port: 18081
  ssl:
    enabled-protocols: TLSv1.2,TLSv1.3
    enabled: false
spring:
  application:
    name: Dialer
  config:
    import: "optional:configserver:"
  cloud:
    config:
#      zookeeper:
#        connect-string: 192.168.4.251:32770
      server:
        native:
          search-locations: classpath:/config
#        git:
#          uri: https://github.com/spring-cloud-samples/config-repo
#      profile: dev
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: 1234567
    driverClassName: org.h2.Driver
    tomcat:
      resources:
        use-vfs: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    properties:
      hibernate.native_support: true
      hibernate.dialect: org.hibernate.dialect.H2Dialect
      hibernate.show_sql: false
      hibernate.format_sql: true
      hibernate.use_sql_comments: true
info:
  hosts:
    - command: docker exec ev0 expressvpn
      name: ev0
      local-host: false
      proxy-host: 192.168.8.164
      proxy-port: 1087
    - command: docker exec ev expressvpn
      name: ev
      local-host: false
      proxy-host: 192.168.8.164
      proxy-port: 1088
  urls:
    - https://youtube.com
    - https://twitter.com
    - https://x.com
    - https://google.com
    - https://t66y.com
    - https://baidu.com
  tolerance: 1
