server:
  port: 18081
  ssl:
    enabled-protocols: TLSv1.2,TLSv1.3
    enabled: false
spring:
  application:
    name: Dialer
  config:
    import: "optional:configserver:"
  cloud:
    zookeeper:
      connect-string: "192.168.4.84:2181"
      discovery:
        enabled: true
        register: true
        root: /big-serv
      config:
        enabled: true
        root: /big-conf
        defaultContext: application
        profile-separator: ','
    config:
      server:
        native:
          search-locations: classpath:/config
#        git:
#          uri: https://github.com/spring-cloud-samples/config-repo
#      profile: dev
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: 1234567
    driverClassName: org.h2.Driver
    tomcat:
      resources:
        # noinspection SpringBootApplicationYaml
        use-vfs: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        native_support: true
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: false
        format_sql: true
        use_sql_comments: true
        compile-time-hibernate-proxies: true
        bytecode:
          provider: javassist
info:
  hosts:
    - command: expressvpn
      name: base
      local-host: true
      enabled: false
    - command: ssh 192.168.4.90 expressvpn
      name: air
      local-host: false
      proxy-host: 192.168.4.90
      proxy-port: 60987
      enabled: true
    - command: docker exec ev0 expressvpn
      name: ev0
      local-host: false
      proxy-host: 192.168.8.164
      proxy-port: 1087
      enabled: false
    - command: docker exec ev expressvpn
      name: ev
      local-host: false
      proxy-host: 192.168.8.164
      proxy-port: 1088
      enabled: false
    - command: ssh root@101.132.187.60
      name: ali
      local-host: false
      proxy-host: 192.168.8.248
      proxy-port: 20171
      enabled: false
  urls:
    - https://youtube.com
    - https://twitter.com
    - https://x.com
    - https://google.com
    - https://t66y.com
    - https://baidu.com
  tolerance: 1
  interval: 6
